// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtvscywapbclgwdariir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0dnNjeXdhcGJjbGd3ZGFyaWlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NTE0NTgsImV4cCI6MjA2MjQyNzQ1OH0.Yx-u-EcyZ4sad1lBWj4V761H6Q4i5G5V9HE1sajsQUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);